stages:
  - release

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running the release job for $CI_COMMIT_TAG."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'v$CI_COMMIT_TAG'
    description: INCREMENTAL_CHANGELOG.md

