stages:
    - release

release:
  stage: release
  image: python:3.9  
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -  
    - export PATH="$HOME/.local/bin:$PATH"  
    - poetry install --no-dev  
    - pip install python-semantic-release  
    - git fetch --tags
    - git tag -l
    - git fetch origin +refs/heads/*:refs/remotes/origin/*  
    - git checkout ${CI_COMMIT_REF_NAME}  
  script:
    - semantic-release publish  
  only:
    - main  
  variables:
    GL_TOKEN: $CI_JOB_TOKEN  
    GITLAB_TOKEN: $CI_JOB_TOKEN