stages:
  - release

release:
  stage: release
  image: python:3.9  
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -  
    - export PATH="$HOME/.local/bin:$PATH"  
    - poetry install --no-dev  
    - pip install python-semantic-release  
    - git fetch --tags  
  script:
    - export BRANCH_NAME=${CI_COMMIT_REF_NAME}  
    - semantic-release publish --branch ${BRANCH_NAME}  
  only:
    - main  
  variables:
    GL_TOKEN: $CI_JOB_TOKEN  

