[tool.poetry]
name = "ploutos"
version = "0.0.0"
description = ""
authors = ["Jérémy Bon <jeremy.bon1069@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
isort = "^5.13.2"
cz-conventional-gitmoji = "^0.6.1"
nordigen = "^1.4.1"
pandas = "^2.2.3"
pydantic = "^2.11.5"
pydantic-settings = "^2.9.1"
uvicorn = "^0.34.2"
loguru = "^0.7.3"
fastapi = "^0.115.12"


[tool.poetry.group.dev.dependencies]
python-semantic-release = "^9.12.0"
isort = "^5.13.2"
commitizen = "^3.30.0"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
version = "0.1.0"
update_changelog_on_bump = true
#name = "cz_gitmoji"
