drop extension if exists "pg_net";

create type "public"."match_type_enum" as enum ('contains', 'starts_with', 'exact', 'regex');

create type "public"."processor_type_enum" as enum ('simple_split', 'loan', 'salary');


  create table "public"."AccountSecrets" (
    "id" bigint generated by default as identity not null,
    "updated_at" timestamp with time zone not null default now(),
    "accountId" uuid,
    "secretId" text not null,
    "bankId" text
      );


alter table "public"."AccountSecrets" enable row level security;


  create table "public"."Accounts" (
    "accountId" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "name" text default ''::text,
    "original_amount" numeric default '0'::numeric,
    "category" text default 'Unknown'::text,
    "sub_category" text default 'Unknown'::text,
    "is_real" boolean default false,
    "active" boolean not null default true
      );



  create table "public"."CategorizationRules" (
    "ruleId" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "description" text,
    "enabled" boolean not null default true,
    "priority" integer not null default 0,
    "account_ids" jsonb,
    "processor_type" public.processor_type_enum not null,
    "processor_config" jsonb not null,
    "last_applied_at" timestamp without time zone,
    "condition_groups" jsonb not null
      );



  create table "public"."RejectedTransferPairs" (
    "pair_id" uuid not null default gen_random_uuid(),
    "transaction_id_1" uuid not null,
    "transaction_id_2" uuid not null,
    "rejected_at" timestamp without time zone default now(),
    "rejected_reason" text
      );



  create table "public"."RuleApplications" (
    "applicationId" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "ruleId" uuid not null,
    "transactionId" uuid not null,
    "applied_at" timestamp without time zone not null default now(),
    "slaves_created" jsonb,
    "success" boolean not null default true,
    "error_message" text
      );



  create table "public"."Transactions" (
    "transactionId" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "description" text,
    "date" timestamp without time zone,
    "type" text,
    "amount" numeric,
    "accountId" uuid default gen_random_uuid()
      );



  create table "public"."TransactionsSlaves" (
    "slaveId" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone,
    "type" text,
    "amount" double precision default '0'::double precision,
    "date" timestamp without time zone,
    "accountId" uuid default gen_random_uuid(),
    "masterId" uuid default gen_random_uuid()
      );


CREATE UNIQUE INDEX "AccountSecrets_pkey" ON public."AccountSecrets" USING btree (id);

CREATE UNIQUE INDEX "Accounts_pkey" ON public."Accounts" USING btree ("accountId");

CREATE UNIQUE INDEX "CategorizationRules_pkey" ON public."CategorizationRules" USING btree ("ruleId");

CREATE UNIQUE INDEX "RejectedTransferPairs_pkey" ON public."RejectedTransferPairs" USING btree (pair_id);

CREATE UNIQUE INDEX "RuleApplications_pkey" ON public."RuleApplications" USING btree ("applicationId");

CREATE UNIQUE INDEX "TransactionsSlaves_pkey" ON public."TransactionsSlaves" USING btree ("slaveId");

CREATE UNIQUE INDEX "Transactions_pkey" ON public."Transactions" USING btree ("transactionId");

CREATE INDEX idx_rejected_pairs_tx1 ON public."RejectedTransferPairs" USING btree (transaction_id_1);

CREATE INDEX idx_rejected_pairs_tx2 ON public."RejectedTransferPairs" USING btree (transaction_id_2);

CREATE UNIQUE INDEX unique_pair ON public."RejectedTransferPairs" USING btree (transaction_id_1, transaction_id_2);

alter table "public"."AccountSecrets" add constraint "AccountSecrets_pkey" PRIMARY KEY using index "AccountSecrets_pkey";

alter table "public"."Accounts" add constraint "Accounts_pkey" PRIMARY KEY using index "Accounts_pkey";

alter table "public"."CategorizationRules" add constraint "CategorizationRules_pkey" PRIMARY KEY using index "CategorizationRules_pkey";

alter table "public"."RejectedTransferPairs" add constraint "RejectedTransferPairs_pkey" PRIMARY KEY using index "RejectedTransferPairs_pkey";

alter table "public"."RuleApplications" add constraint "RuleApplications_pkey" PRIMARY KEY using index "RuleApplications_pkey";

alter table "public"."Transactions" add constraint "Transactions_pkey" PRIMARY KEY using index "Transactions_pkey";

alter table "public"."TransactionsSlaves" add constraint "TransactionsSlaves_pkey" PRIMARY KEY using index "TransactionsSlaves_pkey";

alter table "public"."AccountSecrets" add constraint "AccountSecrets_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES public."Accounts"("accountId") not valid;

alter table "public"."AccountSecrets" validate constraint "AccountSecrets_accountId_fkey";

alter table "public"."Accounts" add constraint "Accounts_active_check" CHECK ((active = ANY (ARRAY[true, false]))) not valid;

alter table "public"."Accounts" validate constraint "Accounts_active_check";

alter table "public"."RejectedTransferPairs" add constraint "RejectedTransferPairs_transaction_id_1_fkey" FOREIGN KEY (transaction_id_1) REFERENCES public."Transactions"("transactionId") ON DELETE CASCADE not valid;

alter table "public"."RejectedTransferPairs" validate constraint "RejectedTransferPairs_transaction_id_1_fkey";

alter table "public"."RejectedTransferPairs" add constraint "RejectedTransferPairs_transaction_id_2_fkey" FOREIGN KEY (transaction_id_2) REFERENCES public."Transactions"("transactionId") ON DELETE CASCADE not valid;

alter table "public"."RejectedTransferPairs" validate constraint "RejectedTransferPairs_transaction_id_2_fkey";

alter table "public"."RejectedTransferPairs" add constraint "ordered_ids" CHECK ((transaction_id_1 < transaction_id_2)) not valid;

alter table "public"."RejectedTransferPairs" validate constraint "ordered_ids";

alter table "public"."RejectedTransferPairs" add constraint "unique_pair" UNIQUE using index "unique_pair";

alter table "public"."RuleApplications" add constraint "fk_rule" FOREIGN KEY ("ruleId") REFERENCES public."CategorizationRules"("ruleId") ON DELETE CASCADE not valid;

alter table "public"."RuleApplications" validate constraint "fk_rule";

alter table "public"."RuleApplications" add constraint "fk_transaction" FOREIGN KEY ("transactionId") REFERENCES public."Transactions"("transactionId") ON DELETE CASCADE not valid;

alter table "public"."RuleApplications" validate constraint "fk_transaction";

alter table "public"."Transactions" add constraint "Transactions_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES public."Accounts"("accountId") ON UPDATE CASCADE not valid;

alter table "public"."Transactions" validate constraint "Transactions_accountId_fkey";

alter table "public"."TransactionsSlaves" add constraint "TransactionsSlaves_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES public."Accounts"("accountId") ON UPDATE CASCADE not valid;

alter table "public"."TransactionsSlaves" validate constraint "TransactionsSlaves_accountId_fkey";

alter table "public"."TransactionsSlaves" add constraint "TransactionsSlaves_masterId_fkey" FOREIGN KEY ("masterId") REFERENCES public."Transactions"("transactionId") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."TransactionsSlaves" validate constraint "TransactionsSlaves_masterId_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_total_amount_by_account_ids(account_ids uuid[])
 RETURNS TABLE("accountId" uuid, total_amount numeric, max_date timestamp with time zone)
 LANGUAGE sql
AS $function$SELECT
        "accountId",
        SUM(
            "amount" * CASE
                WHEN "type" = 'debit' THEN -1
                ELSE 1
            END
        ) AS total_amount,
        MAX("date") AS max_date
    FROM (
        SELECT
            "accountId",
            "amount",
            "type",
            "date"
        FROM "Transactions"
        WHERE "accountId" = ANY(account_ids)

        UNION ALL

        SELECT
            "accountId",
            "amount",
            "type",
            NULL AS "date"
        FROM "TransactionsSlaves"
        WHERE "accountId" = ANY(account_ids)
    ) AS combined_transactions
    GROUP BY "accountId";$function$
;

CREATE OR REPLACE FUNCTION public.get_transactions(p_date_from date DEFAULT NULL::date, p_date_to date DEFAULT NULL::date, p_account_id uuid DEFAULT NULL::uuid)
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    result JSON;
BEGIN
    SELECT json_agg(transaction_data)
    INTO result
    FROM (
        SELECT
            t."transactionId",
            t.created_at,
            t.updated_at,
            t.description,
            t.date,
            t.type,
            t.amount,
            t."accountId",
            ma.name AS "masterAccountName",
            ma.is_real AS "masterAccountIsReal",
            COALESCE(
                (
                    SELECT json_agg(
                        json_build_object(
                            'slaveId', ts."slaveId",
                            'type', ts.type,
                            'amount', ts.amount,
                            'date', ts.date,
                            'accountId', ts."accountId",
                            'masterId', ts."masterId",
                            'slaveAccountName', sa.name,
                            'slaveAccountIsReal', sa.is_real
                        )
                    )
                    FROM "TransactionsSlaves" ts
                    LEFT JOIN "Accounts" sa ON ts."accountId" = sa."accountId"
                    WHERE ts."masterId" = t."transactionId"
                ),
                '[]'::json
            ) AS "TransactionsSlaves"
        FROM "Transactions" t
        LEFT JOIN "Accounts" ma ON t."accountId" = ma."accountId"
        WHERE
            (p_date_from IS NULL OR t.date >= p_date_from)
            AND (p_date_to IS NULL OR t.date <= p_date_to)
            AND (
                p_account_id IS NULL
                OR t."accountId" = p_account_id
                OR EXISTS (
                    SELECT 1 FROM "TransactionsSlaves" ts2
                    WHERE ts2."masterId" = t."transactionId"
                    AND ts2."accountId" = p_account_id
                )
            )
        ORDER BY t.date DESC, t.created_at DESC
    ) AS transaction_data;

    RETURN COALESCE(result, '[]'::json);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_transfer_candidates()
 RETURNS TABLE(transactionid_1 uuid, description_1 text, date_1 timestamp without time zone, type_1 text, amount_1 numeric, accountid_1 uuid, accountname_1 text, transactionid_2 uuid, description_2 text, date_2 timestamp without time zone, type_2 text, amount_2 numeric, accountid_2 uuid, accountname_2 text)
 LANGUAGE sql
AS $function$WITH transaction AS (
        SELECT 
            t."transactionId",
            t."description",
            t."date",
            t."type",
            t."amount",
            t."accountId",
            ts."slaveId",
            ts."masterId",
            ts."accountId" AS slave_accountId,
            ts."amount" AS slave_amount,
            ts."type" AS slave_type,
            ts."date" AS slave_date,
            a."is_real" AS slave_account_is_real
        FROM 
            "Transactions" t
        LEFT JOIN 
            "TransactionsSlaves" ts ON t."transactionId" = ts."masterId"
        LEFT JOIN 
            "Accounts" a ON ts."accountId" = a."accountId"
        WHERE 
            a."is_real" = false
            AND ts."amount" = t."amount"
    )
    SELECT 
        t1."transactionId" AS transactionId_1,
        t1."description" AS description_1,
        t1."date" AS date_1,
        t1."type" AS type_1,
        t1."amount" AS amount_1,
        t1."accountId" AS accountId_1,
        acc1."name" AS accountName_1,
        t2."transactionId" AS transactionId_2,
        t2."description" AS description_2,
        t2."date" AS date_2,
        t2."type" AS type_2,
        t2."amount" AS amount_2,
        t2."accountId" AS accountId_2,
        acc2."name" AS accountName_2
    FROM 
        transaction t1
    INNER JOIN 
        transaction t2 
        ON t1."date"::date = t2."date"::date
        AND t1."transactionId" > t2."transactionId"
        AND t1."slave_type" = t2."type"
        AND t1."type" != t2."type" 
        AND t1."amount" = t2."amount"
        AND t1."accountId"!=t2."accountId"
    LEFT JOIN 
        "Accounts" acc1 ON t1."accountId" = acc1."accountId"
    LEFT JOIN 
        "Accounts" acc2 ON t2."accountId" = acc2."accountId"
    WHERE NOT EXISTS (
        SELECT 1 
        FROM "RejectedTransferPairs" rtp
        WHERE rtp."transaction_id_1" = LEAST(t1."transactionId", t2."transactionId")
          AND rtp."transaction_id_2" = GREATEST(t1."transactionId", t2."transactionId")
    )$function$
;

CREATE OR REPLACE FUNCTION public.match_transactions_regex(regex_pattern text, account_ids uuid[] DEFAULT NULL::uuid[], transaction_type text DEFAULT NULL::text)
 RETURNS TABLE("transactionId" uuid, "accountId" uuid, description text, amount numeric, date timestamp without time zone, type text, created_at timestamp with time zone, updated_at timestamp without time zone)
 LANGUAGE plpgsql
AS $function$
begin
  return query
  select 
    t."transactionId",
    t."accountId",
    t.description,
    t.amount,
    t.date,
    t.type,
    t.created_at,
    t.updated_at
  from "Transactions" t
  inner join "TransactionsSlaves" ts on ts."masterId" = t."transactionId"
  inner join "Accounts" a on a."accountId" = ts."accountId"
  where t.description ~* regex_pattern
    and a.name = 'Unknown'
    and a.category = 'Unknown'
    and a.sub_category = 'Unknown'
    and a.is_real = false
    and (account_ids is null or t."accountId" = any(account_ids))
    and (transaction_type is null or transaction_type = 'all' or t.type = transaction_type);
end;
$function$
;

grant delete on table "public"."AccountSecrets" to "anon";

grant insert on table "public"."AccountSecrets" to "anon";

grant references on table "public"."AccountSecrets" to "anon";

grant select on table "public"."AccountSecrets" to "anon";

grant trigger on table "public"."AccountSecrets" to "anon";

grant truncate on table "public"."AccountSecrets" to "anon";

grant update on table "public"."AccountSecrets" to "anon";

grant delete on table "public"."AccountSecrets" to "authenticated";

grant insert on table "public"."AccountSecrets" to "authenticated";

grant references on table "public"."AccountSecrets" to "authenticated";

grant select on table "public"."AccountSecrets" to "authenticated";

grant trigger on table "public"."AccountSecrets" to "authenticated";

grant truncate on table "public"."AccountSecrets" to "authenticated";

grant update on table "public"."AccountSecrets" to "authenticated";

grant delete on table "public"."AccountSecrets" to "service_role";

grant insert on table "public"."AccountSecrets" to "service_role";

grant references on table "public"."AccountSecrets" to "service_role";

grant select on table "public"."AccountSecrets" to "service_role";

grant trigger on table "public"."AccountSecrets" to "service_role";

grant truncate on table "public"."AccountSecrets" to "service_role";

grant update on table "public"."AccountSecrets" to "service_role";

grant delete on table "public"."Accounts" to "anon";

grant insert on table "public"."Accounts" to "anon";

grant references on table "public"."Accounts" to "anon";

grant select on table "public"."Accounts" to "anon";

grant trigger on table "public"."Accounts" to "anon";

grant truncate on table "public"."Accounts" to "anon";

grant update on table "public"."Accounts" to "anon";

grant delete on table "public"."Accounts" to "authenticated";

grant insert on table "public"."Accounts" to "authenticated";

grant references on table "public"."Accounts" to "authenticated";

grant select on table "public"."Accounts" to "authenticated";

grant trigger on table "public"."Accounts" to "authenticated";

grant truncate on table "public"."Accounts" to "authenticated";

grant update on table "public"."Accounts" to "authenticated";

grant delete on table "public"."Accounts" to "service_role";

grant insert on table "public"."Accounts" to "service_role";

grant references on table "public"."Accounts" to "service_role";

grant select on table "public"."Accounts" to "service_role";

grant trigger on table "public"."Accounts" to "service_role";

grant truncate on table "public"."Accounts" to "service_role";

grant update on table "public"."Accounts" to "service_role";

grant delete on table "public"."CategorizationRules" to "anon";

grant insert on table "public"."CategorizationRules" to "anon";

grant references on table "public"."CategorizationRules" to "anon";

grant select on table "public"."CategorizationRules" to "anon";

grant trigger on table "public"."CategorizationRules" to "anon";

grant truncate on table "public"."CategorizationRules" to "anon";

grant update on table "public"."CategorizationRules" to "anon";

grant delete on table "public"."CategorizationRules" to "authenticated";

grant insert on table "public"."CategorizationRules" to "authenticated";

grant references on table "public"."CategorizationRules" to "authenticated";

grant select on table "public"."CategorizationRules" to "authenticated";

grant trigger on table "public"."CategorizationRules" to "authenticated";

grant truncate on table "public"."CategorizationRules" to "authenticated";

grant update on table "public"."CategorizationRules" to "authenticated";

grant delete on table "public"."CategorizationRules" to "service_role";

grant insert on table "public"."CategorizationRules" to "service_role";

grant references on table "public"."CategorizationRules" to "service_role";

grant select on table "public"."CategorizationRules" to "service_role";

grant trigger on table "public"."CategorizationRules" to "service_role";

grant truncate on table "public"."CategorizationRules" to "service_role";

grant update on table "public"."CategorizationRules" to "service_role";

grant delete on table "public"."RejectedTransferPairs" to "anon";

grant insert on table "public"."RejectedTransferPairs" to "anon";

grant references on table "public"."RejectedTransferPairs" to "anon";

grant select on table "public"."RejectedTransferPairs" to "anon";

grant trigger on table "public"."RejectedTransferPairs" to "anon";

grant truncate on table "public"."RejectedTransferPairs" to "anon";

grant update on table "public"."RejectedTransferPairs" to "anon";

grant delete on table "public"."RejectedTransferPairs" to "authenticated";

grant insert on table "public"."RejectedTransferPairs" to "authenticated";

grant references on table "public"."RejectedTransferPairs" to "authenticated";

grant select on table "public"."RejectedTransferPairs" to "authenticated";

grant trigger on table "public"."RejectedTransferPairs" to "authenticated";

grant truncate on table "public"."RejectedTransferPairs" to "authenticated";

grant update on table "public"."RejectedTransferPairs" to "authenticated";

grant delete on table "public"."RejectedTransferPairs" to "service_role";

grant insert on table "public"."RejectedTransferPairs" to "service_role";

grant references on table "public"."RejectedTransferPairs" to "service_role";

grant select on table "public"."RejectedTransferPairs" to "service_role";

grant trigger on table "public"."RejectedTransferPairs" to "service_role";

grant truncate on table "public"."RejectedTransferPairs" to "service_role";

grant update on table "public"."RejectedTransferPairs" to "service_role";

grant delete on table "public"."RuleApplications" to "anon";

grant insert on table "public"."RuleApplications" to "anon";

grant references on table "public"."RuleApplications" to "anon";

grant select on table "public"."RuleApplications" to "anon";

grant trigger on table "public"."RuleApplications" to "anon";

grant truncate on table "public"."RuleApplications" to "anon";

grant update on table "public"."RuleApplications" to "anon";

grant delete on table "public"."RuleApplications" to "authenticated";

grant insert on table "public"."RuleApplications" to "authenticated";

grant references on table "public"."RuleApplications" to "authenticated";

grant select on table "public"."RuleApplications" to "authenticated";

grant trigger on table "public"."RuleApplications" to "authenticated";

grant truncate on table "public"."RuleApplications" to "authenticated";

grant update on table "public"."RuleApplications" to "authenticated";

grant delete on table "public"."RuleApplications" to "service_role";

grant insert on table "public"."RuleApplications" to "service_role";

grant references on table "public"."RuleApplications" to "service_role";

grant select on table "public"."RuleApplications" to "service_role";

grant trigger on table "public"."RuleApplications" to "service_role";

grant truncate on table "public"."RuleApplications" to "service_role";

grant update on table "public"."RuleApplications" to "service_role";

grant delete on table "public"."Transactions" to "anon";

grant insert on table "public"."Transactions" to "anon";

grant references on table "public"."Transactions" to "anon";

grant select on table "public"."Transactions" to "anon";

grant trigger on table "public"."Transactions" to "anon";

grant truncate on table "public"."Transactions" to "anon";

grant update on table "public"."Transactions" to "anon";

grant delete on table "public"."Transactions" to "authenticated";

grant insert on table "public"."Transactions" to "authenticated";

grant references on table "public"."Transactions" to "authenticated";

grant select on table "public"."Transactions" to "authenticated";

grant trigger on table "public"."Transactions" to "authenticated";

grant truncate on table "public"."Transactions" to "authenticated";

grant update on table "public"."Transactions" to "authenticated";

grant delete on table "public"."Transactions" to "service_role";

grant insert on table "public"."Transactions" to "service_role";

grant references on table "public"."Transactions" to "service_role";

grant select on table "public"."Transactions" to "service_role";

grant trigger on table "public"."Transactions" to "service_role";

grant truncate on table "public"."Transactions" to "service_role";

grant update on table "public"."Transactions" to "service_role";

grant delete on table "public"."TransactionsSlaves" to "anon";

grant insert on table "public"."TransactionsSlaves" to "anon";

grant references on table "public"."TransactionsSlaves" to "anon";

grant select on table "public"."TransactionsSlaves" to "anon";

grant trigger on table "public"."TransactionsSlaves" to "anon";

grant truncate on table "public"."TransactionsSlaves" to "anon";

grant update on table "public"."TransactionsSlaves" to "anon";

grant delete on table "public"."TransactionsSlaves" to "authenticated";

grant insert on table "public"."TransactionsSlaves" to "authenticated";

grant references on table "public"."TransactionsSlaves" to "authenticated";

grant select on table "public"."TransactionsSlaves" to "authenticated";

grant trigger on table "public"."TransactionsSlaves" to "authenticated";

grant truncate on table "public"."TransactionsSlaves" to "authenticated";

grant update on table "public"."TransactionsSlaves" to "authenticated";

grant delete on table "public"."TransactionsSlaves" to "service_role";

grant insert on table "public"."TransactionsSlaves" to "service_role";

grant references on table "public"."TransactionsSlaves" to "service_role";

grant select on table "public"."TransactionsSlaves" to "service_role";

grant trigger on table "public"."TransactionsSlaves" to "service_role";

grant truncate on table "public"."TransactionsSlaves" to "service_role";

grant update on table "public"."TransactionsSlaves" to "service_role";


